require 'net/http'
require 'uri'

movie_list = ["The+Shawshank+Redemption",
"The+Godfather",
"The+Godfather:+Part+II",
"The+Dark+Knight",
"12+Angry+Men",
"Schindler's+List",
"Pulp+Fiction",
"The+Lord+of+the+Rings:+The+Return+of+the+King",
"The+Good,+the+Bad+and+the+Ugly",
"Fight+Club",
"The+Lord+of+the+Rings:+The+Fellowship+of+the+Ring",
"Star+Wars:+Episode+V+-+The+Empire+Strikes+Back",
"Forrest+Gump",
"Inception",
"The+Lord+of+the+Rings:+The+Two+Towers",
"One+Flew+Over+the+Cuckoo's+Nest",
"Goodfellas",
"The+Matrix",
"Seven+Samurai",
"Star+Wars:+Episode+IV+-+A+New+Hope",
"City+of+God",
"Se7en",
"The+Silence+of+the+Lambs",
"It's+a+Wonderful+Life",
"The+Usual+Suspects",
"Life+Is+Beautiful",
"La+La+Land",
"Leon:+The+Professional",
"Spirited+Away",
"Saving+Private+Ryan",
"Once+Upon+a+Time+in+the+West",
"American+History+X",
"Interstellar",
"Casablanca",
"Psycho",
"City+Lights",
"The+Green+Mile",
"Raiders+of+the+Lost+Ark",
"The+Intouchables",
"Modern+Times",
"Rear+Window",
"The+Departed",
"The+Pianist",
"Terminator+2:+Judgment+Day",
"Back+to+the+Future",
"Whiplash",
"Gladiator",
"Memento",
"Apocalypse+Now",
"The+Prestige",
"The+Lion+King",
"Alien",
"Dr.+Strangelove+or:+How+I+Learned+to+Stop+Worrying+and+Love+the+Bomb",
"Sunset+Boulevard",
"The+Great+Dictator",
"The+Lives+of+Others",
"Cinema+Paradiso"
]
# User.create(
#     username: not_trusted,
#     email: not_trusted@nottrusted.com,
#     password: 'password',
#     trusted_reviewer: false
#   )

# User.create(
#     username: test_user,
#     email: test_user@test.com,
#     password: 'password',
#     trusted_reviewer: true
#   )

categories = ['Horror', 'Drama', 'Comedy', 'Sci-Fi', 'Suspense']

categories.each do |category|
  Category.create(genre: category)
end

movie_list.each do |title|
  p "PROCESSING #{title}..."
  uri = URI.parse("http://www.omdbapi.com/?t=#{title}&y=&plot=full&r=json")
  movie_info = Net::HTTP.get_response(uri)
    parsed_info = JSON.parse(movie_info.body)
    Movie.create(
      title: parsed_info["Title"],
      year: parsed_info["Year"].to_i,
      actors: parsed_info["Actors"],
      runtime: parsed_info["Runtime"],
      plot: parsed_info["Plot"],
      category_id: rand(1..10),
      url: "http://www.omdbapi.com/?t=#{title}&y=&plot=full&r=json",
      img: parsed_info["Poster"]
    )

end


# unused films: "Paths+of+Glory",
              # "Grave+of+the+Fireflies",
              # "Django+Unchained",
              # "The+Shining",
              # "WALL-E",
              # "The+Dark+Knight+Rises",
              # "American+Beauty",
              # "Princess+Mononoke",
              # "Aliens",

# 100.times do
#   Review.create(
#     body: Faker::Hipster.sentence,
#     reviewer_id: rand(6..8),
#     movie_id: rand(1..10)
#   )
# end

# 125.times do
#   Rating.create(
#     score: rand(1..5),
#     rater_id: rand(1..5),
#     review_id: rand(1..100)
#   )
# end
              # "Oldboy",
              # "Once+Upon+a+Time+in+America",
              # "Citizen+Kane",
              # "Das+Boot",
              # "Witness+for+the+Prosecution",
              # "North+by+Northwest",
              # "Vertigo",
              # "Star+Wars:+Episode+VI+-+Return+of+the+Jedi",
              # "Reservoir+Dogs",
              # "Braveheart",
              # "Amelie",
              # "Requiem+for+a+Dream",
              # "A+Clockwork+Orange",
              # "Taxi+Driver",
              # "Lawrence+of+Arabia",
              # "Double+Indemnity",
              # "Like+Stars+on+Earth",
              # "To+Kill+a+Mockingbird",
              # "Eternal+Sunshine+of+the+Spotless+Mind",
              # "Toy+Story+3",
              # "My+Father+and+My+Son",
              # "Amadeus",
              # "Hacksaw+Ridge",
              # "Full+Metal+Jacket",
              # "The+Sting",
              # "2001:+A+Space+Odyssey",
              # "Bicycle+Thieves",
              # "Toy+Story",
              # "Singin'+in+the+Rain",
              # "Snatch",
              # "Inglourious+Basterds",
              # "The+Kid",
              # "Monty+Python+and+the+Holy+Grail",
              # "L.A.+Confidential",
              # "For+a+Few+Dollars+More",
              # "3+Idiots",
              # "Rashomon",
              # "Scarface",
              # "The+Apartment",
              # "The+Hunt",
              # "Indiana+Jones+and+the+Last+Crusade",
              # "A+Separation",
              # "Good+Will+Hunting",
              # "Metropolis",
              # "Arrival",
              # "Yojimbo",
              # "All+About+Eve",
              # "Batman+Begins",
              # "Some+Like+It+Hot",
              # "The+Treasure+of+the+Sierra+Madre",
              # "Up",
              # "Unforgiven",
              # "Downfall",
              # "Raging+Bull",
              # "The+Third+Man",
              # "Die+Hard",
              # "Children+of+Heaven",
              # "The+Great+Escape",
              # "Heat",
              # "Chinatown",
              # "Inside+Out",
              # "Pan's+Labyrinth",
              # "Ikiru",
              # "My+Neighbor+Totoro",
              # "On+the+Waterfront",
              # "Room",
              # "Ran",
              # "The+Gold+Rush",
              # "The+Secret+in+Their+Eyes",
              # "The+Bridge+on+the+River+Kwai",
              # "Mr.+Smith+Goes+to+Washington",
              # "Blade+Runner",
              # "The+Seventh+Seal",
              # "Howl's+Moving+Castle",
              # "Lock,+Stock+and+Two+Smoking+Barrels",
              # "The+Bandit",
              # "A+Wednesday",
              # "Casino",
              # "Judgment+at+Nuremberg",
              # "A+Beautiful+Mind",
              # "Incendies",
              # "The+General",
              # "Wild+Strawberries",
              # "The+Elephant+Man",
              # "Warrior",
              # "V+for+Vendetta",
              # "The+Wolf+of+Wall+Street",
              # "Sunrise",
              # "The+Passion+of+Joan+of+Arc",
              # "Andaz+Apna+Apna",
              # "Hera+Pheri",
              # "Gran+Torino",
              # "Rang+De+Basanti",
              # "The+Big+Lebowski",
              # "Dial+M+for+Murder",
              # "Trainspotting",
              # "The+Deer+Hunter",
              # "Tokyo+Story",
              # "Gone+with+the+Wind",
              # "Fargo",
              # "Munna+Bhai+M.B.B.S.",
              # "Finding+Nemo",
              # "Sholay",
              # "The+Sixth+Sense",
              # "Cool+Hand+Luke",
              # "The+Thing",
              # "Rebecca",
              # "No+Country+for+Old+Men",
              # "How+to+Train+Your+Dragon",
              # "Into+the+Wild",
              # "Kill+Bill:+Vol.+1",
              # "Mary+and+Max",
              # "Gone+Girl",
              # "There+Will+Be+Blood",
              # "Come+and+See",
              # "It+Happened+One+Night",
              # "Life+of+Brian",
              # "Rush",
              # "Hotel+Rwanda",
              # "Platoon",
              # "Star+Wars:+The+Force+Awakens",
              # "Shutter+Island",
              # "Network",
              # "The+Wages+of+Fear",
              # "The+Nights+of+Cabiria",
              # "Spotlight",
              # "Stand+by+Me",
              # "In+the+Name+of+the+Father",
              # "Wild+Tales",
              # "Butch+Cassidy+and+the+Sundance+Kid",
              # "The+400+Blows",
              # "Mad+Max:+Fury+Road",
              # "The+Maltese+Falcon",
              # "12+Years+a+Slave",
              # "The+Grand+Budapest+Hotel",
              # "Ben-Hur",
              # "Million+Dollar+Baby",
              # "Persona",
              # "Amores+Perros",
              # "Drishyam",
              # "The+Princess+Bride",
              # "Jurassic+Park",
              # "Hachi:+A+Dog's+Tale",
              # "Memories+of+Murder",
              # "Nausicaa+of+the+Valley+of+the+Wind",
              # "Stalker",
              # "The+Truman+Show",
              # "The+Grapes+of+Wrath",
              # "The+Message",
              # "Touch+of+Evil",
              # "Before+Sunrise",
              # "Annie+Hall",
              # "Gandhi",
              # "Rocky",
              # "Rogue+One:+A+Star+Wars+Story",
              # "The+Bourne+Ultimatum",
              # "Harry+Potter+and+the+Deathly+Hallows:+Part+2",
              # "Diabolique",
              # "Donnie+Darko",
              # "Monsters,+Inc.",
              # "Superman",
              # "Udaan",
              # "The+Wizard+of+Oz",
              # "Zootopia",
              # "The+Terminator",
              # "Prisoners",
              # "Groundhog+Day",
              # "Twelve+Monkeys",
              # "Catch+Me+If+You+Can",
              # "Jaws",
              # "Barry+Lyndon",
              # "La+Haine",
              # "The+Best+Years+of+Our+Lives",
              # "Infernal+Affairs",
              # "Chak+de!+India",
              # "Strangers+on+a+Train",
              # "Dog+Day+Afternoon",
              # "The+Battle+of+Algiers",
              # "Sin+City",
              # "Kind+Hearts+and+Coronets",
              # "The+Help",
              # "The+Imitation+Game"
